name: CI/CD Pipeline for Heart Attack Predictor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests (add actual test commands if available)"
          python -c "import app; print('App imports successfully')"

      - name: Build Docker image
        run: |
          docker build -t heart-attack-predictor:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag heart-attack-predictor:${{ github.sha }} <your-docker-hub-username>/heart-attack-predictor:${{ github.sha }}
          docker push <your-docker-hub-username>/heart-attack-predictor:${{ github.sha }}

  deploy-to-heroku:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Heroku Container Registry
        run: |
          heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Set Heroku stack to container
        run: |
          heroku stack:set container -a heart-attack-predictor
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull <your-docker-hub-username>/heart-attack-predictor:${{ github.sha }}

      - name: Push to Heroku Container Registry
        run: |
          heroku container:push web -a heart-attack-predictor
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release to Heroku
        run: |
          heroku container:release web -a heart-attack-predictor
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}